// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnmM_XorRcWc9g0oHg3V0zBK-9n9bbkjY',
    appId: '1:187162339964:web:15f14a7fef55c0100637f9',
    messagingSenderId: '187162339964',
    projectId: 'lanking-48f83',
    authDomain: 'lanking-48f83.firebaseapp.com',
    databaseURL: 'https://lanking-48f83-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lanking-48f83.appspot.com',
    measurementId: 'G-E45RLPZMS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF70w2N7KyzGoQKZR4qLMRBuKtT_vkfCs',
    appId: '1:187162339964:android:4950f23c64da4dc30637f9',
    messagingSenderId: '187162339964',
    projectId: 'lanking-48f83',
    databaseURL: 'https://lanking-48f83-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lanking-48f83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjUdkFvG-tz4mU3a-RIbbPIMTncJuqBM4',
    appId: '1:187162339964:ios:286bfc7ba20fda6b0637f9',
    messagingSenderId: '187162339964',
    projectId: 'lanking-48f83',
    databaseURL: 'https://lanking-48f83-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lanking-48f83.appspot.com',
    iosClientId: '187162339964-v7fu38cmdacgj9i64hf7hihgp340r7j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.angelLanking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjUdkFvG-tz4mU3a-RIbbPIMTncJuqBM4',
    appId: '1:187162339964:ios:286bfc7ba20fda6b0637f9',
    messagingSenderId: '187162339964',
    projectId: 'lanking-48f83',
    databaseURL: 'https://lanking-48f83-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lanking-48f83.appspot.com',
    iosClientId: '187162339964-v7fu38cmdacgj9i64hf7hihgp340r7j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.angelLanking',
  );
}
